import cv2
import os
import re
import pandas as pd
from paddleocr import PaddleOCR  # <-- Modern Deep Learning OCR

# --- SECTION 3.6: INITIALIZE DEEP LEARNING OCR MODEL ---
# PaddleOCR v3.0+ automatically manages its backend processing device!
ocr_model = PaddleOCR(use_angle_cls=False, lang='en', use_gpu=False)

# --- SECTION 3.7: DATA PARSING & CLEANING FUNCTIONS ---

def clean_ocr_text(text):
    """Fixes common character hallucinations before running regex."""
    # Swap 'O' or 'o' to '0' if it sits directly inside a number (e.g., 1O.5O -> 10.50)
    text = re.sub(r'(?<=\d)[Oo](?=\d)', '0', text)
    return text

def extract_total(text):
    text = clean_ocr_text(text)
    
    # Target common financial keywords
    keywords = r'(total|amount due|net|grand total|cash|paid|rm|amount)'
    lines = text.split('\n')
    possible_totals = []
    
    for line in lines:
        if re.search(keywords, line.lower()):
            # Find standardized decimal structures (e.g., 12.50)
            numbers = re.findall(r'\d+\.\d{2}', line)
            if numbers:
                possible_totals.append(float(numbers[0]))
                
    if possible_totals:
        return max(possible_totals)
    
    # Fallback: Grab the largest decimal number printed anywhere on the page
    all_decimals = re.findall(r'\d+\.\d{2}', text)
    if all_decimals:
        return max([float(x) for x in all_decimals])
        
    return 0.0  # Return 0.0 if nothing resembling a price structure can be found

def extract_date(text):
    # Match standard numeric date formats: DD/MM/YYYY, YYYY-MM-DD, DD-MM-YYYY, etc.
    date_pattern = r'(\d{1,4}[-/.]\d{1,2}[-/.]\d{2,4})'
    matches = re.findall(date_pattern, text)
    if matches:
        return matches[0]
    return "Unknown"

# --- MAIN EXECUTION PIPELINE ---

if __name__ == "__main__":
    # Pointing directly to your combined training data as requested!
    input_folder = "data/processed_data/combined_train"
    output_text_folder = "data/extracted_text/extracted_combined_train"
    
    os.makedirs(output_text_folder, exist_ok=True)
    print("Pipeline Initiated. Running modern Deep Learning Extraction Engine...")

    # Array to compile structured data for the final dataset output
    parsed_dataset = []

    # Check if folder exists to avoid missing path crashes
    if not os.path.exists(input_folder):
        print(f"❌ Error: The folder path '{input_folder}' does not exist.")
        exit()

    for filename in os.listdir(input_folder):
        if filename.lower().endswith((".png", ".jpg", ".jpeg")):
            image_path = os.path.join(input_folder, filename)

            # 1. Read Image
            img = cv2.imread(image_path)
            if img is None:
                print(f"⚠️ Could not read image: {filename}")
                continue

            # 2. Extract Text via Deep Learning Pipeline
            result = ocr_model.ocr(image_path)
            
            # Reconstruct text entries into lines cleanly
            extracted_lines = []
            if result and isinstance(result, list):
                # Handle cases where nested list arrays are generated by the model backend
                for block in result:
                    if block is None: continue
                    for line in block:
                        text_content = line[1][0]  # Extract just the recognized text string
                        extracted_lines.append(text_content)
            
            extracted_text = "\n".join(extracted_lines)

            # 3. Save Raw Text Document (For verification / audit trail)
            text_filename = os.path.splitext(filename)[0] + ".txt"
            output_text_path = os.path.join(output_text_folder, text_filename)
            with open(output_text_path, "w", encoding="utf-8") as f:
                f.write(extracted_text)

            # 4. Apply Regex Parsers to the Structured Text String
            predicted_total = extract_total(extracted_text)
            predicted_date = extract_date(extracted_text)

            # 5. Append Results to Dataset Array
            parsed_dataset.append({
                "filename": filename,
                "predicted_date": predicted_date,
                "predicted_total": predicted_total
            })

            print(f"Processed: {filename} -> Total: {predicted_total} | Date: {predicted_date}")

    # 6. Save Extracted Data Directly to a CSV for Anomaly Detection (Section 3.8)
    df_output = pd.DataFrame(parsed_dataset)
    output_csv_path = "data/extracted_text/parsed_predictions.csv"
    df_output.to_csv(output_csv_path, index=False)
    
    print("\n" + "="*40)
    print(f"SUCCESS: Pipeline execution complete.")
    print(f"Structured metrics written to: {output_csv_path}")
    print("="*40)